services:
  movies-service:
    profiles:
      - "apps"
    image: reactive-spring-webflux/movies-service
    build:
      context: ./movies-service
    develop:
      watch:
        - action: rebuild
          path: ./movies-service
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    ports:
      - "8082:8082"
      - "5005:5005"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"